### ISSUE TITLE
issueet のエクスポート

### ISSUE THREAD

**Issue by shouh** [shouh/issueet#891]
# 目的
* issueet の issues 全てをエクスポートすることでローカルに保持したい
* エクスポートした issues の形式を整え、repo として公開したい(Github Issue の UI を超える一覧性・視認性を提供したい)

# 挫折理由 in 2016/07/22 09:32:22
エクスポートした issues をどう見せるかは必要になってから考えればいい。どうせ今考えても、必要になった時の要件を満たすとは限らない。

# TODO
* [x] issueet のエクスポート
* [ ] exported issues に対し、repo 用の変換を行うスクリ
* [ ] exported issues をアップロードする repo の整備

**Comment by shouh** [comment]
## :x: export_issues.py では無理やった

https://github.com/shouh/scripts/blob/85fb1c3692c299330355b6296219189c31397827/githubapi/export_issues.py

以下バッチファイル作ってみたんだけど、

```bat
rem @echo off
prompt $$ 

setlocal
set user=shouh
set repo=issueet
set outdir=C:\\data\text\exported_issue\issueet

call %~dp0token.bat
call proxyon.bat

python %~dp0export_issues.py -u %user% -r %repo% -o %outdir%
```

結果はこうなった。

```
(041/890)saving C:\data\text\exported_issue\issueet\#850_sphinx の
コードブロックで ascii art で書いたネットワーク図やらテーブルやらを並べ
てると WARNING Block quote ends without a blank line; unexpected uninden
t. やら WARNING Inline substitution_reference start-string without end-s
tring. やらが出てきて意味不明。コードブロックなんだから閉じるまでは全部
無効にしろよー.md...
Traceback (most recent call last):
  File "C:\work\github\shouh\scripts\githubapi\export_issues.py", line 240, in <module>
    formatter.generate()
  File "C:\work\github\shouh\scripts\githubapi\export_issues.py", line 189, in generate
    util.flexible_encode(content),
  File "C:\work\github\shouh\scripts\githubapi\util.py", line 20, in write_to_file
    f = file(filepath, 'w')
IOError: [Errno 2] No such file or directory: u'C:\\mail\\data\\text\\exported_issue\\issueet\\#850_sphinx \u306e\u30b3\u30fc\u30c9\u30d6\u30ed\u30c3\u30af\u3067 ascii art \u3067\u66f8\u3044\u305f\u30cd\u30c3\u30c8\u30ef\u30fc\u30af\u56f3\u3084\u3089\u30c6\u30fc\u30d6\u30eb\u3084\u3089\u3092\u4e26\u3079\u3066\u308b\u3068 WARNING Block quote ends without a blank line; unexpected unindent. \u3084\u3089 WARNING Inline substitution_reference start-string without end-string. \u3084\u3089\u304c\u51fa\u3066\u304d\u3066\u610f\u5473\u4e0d\u660e\u3002\u30b3\u30fc\u30c9\u30d6\u30ed\u30c3\u30af\u306a\u3093\u3060\u304b\u3089\u9589\u3058\u308b\u307e\u3067\u306f\u5168\u90e8\u7121\u52b9\u306b\u3057\u308d\u3088\u30fc.md'
```

……ファイル名超過やね。issueet tweet は1024文字までなのに対し、ファイル名は255文字以下だものな。

**Comment by shouh** [comment]
## エクスポート代案
ファイル名は issue no のみにして、issue_format.txt に title も加えた上で、いったん出力。で、出力結果に対して、title 部分を取り出して一覧表示するようなスクリを別途書いて実行する……の **二段階プロセス** になるかなあ。

**Comment by shouh** [comment]
# エクスポートしたファイルの中身サンプル

```markdown
# issueet のエクスポート
* [Meta](#meta)
* [Body](#body)
* [Comments](#comments)

# <a name="meta">Meta
* Posted by `shouh`
* Created at 2016-07-11T02:34:18Z
* Labels: todo, TWEET

# <a name="body">Body


# <a name="comments">Comments
# shouh in 2016-07-11T02:41:19Z
last updated 2016-07-11T02:41:19Z

## エクスポート代案
ファイル名は issue no のみにして……
```

**Comment by shouh** [comment]
# repo 用の変換・整備
## output
* :file_folder: root
  * :file_folder: label1
    * :memo: issue_#???.md
    * ...
  * :file_folder:  label2
    * :memo: issue_#???.md
    * ...

**Comment by shouh** [comment]
# upload 用 repo の準備
できれば @shouh/issueet  に置きたいけど、 **万が一消したい場合に repo 毎消すわけにはいかない(issues も消える)** ので **別 repo 作ってそっちにアップ** しましょう。

名前は @shouh/issueet_exported みたいな感じかな。
